### ISSUE TITLE
Restroom filter on map takes user to new page instead of filtering 

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/urban-thrifter#146] opened 2020-11-24 20:51 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I clicked on the Restroom icon on the map, it took me to a new page that maps the public NYC restrooms. I don't know if this is a bug per se, but it's a bit confusing when all of the other icons serve as filtering mechanisms. 

## Expected Behavior
I clicked on the Restroom icon and expected to see markers for public restrooms on the map.

## Current Behavior
I clicked on the Restroom icon and was taken to a new page with a completely different map.

## Ideas for Improvement
It would be great if you can add the public restrooms to the original map.

## Steps to Reproduce

1. Go to the Resource map

2. Click on the Restrooms icon

3. User should be transported to a new map 

## Context (Environment)

Users might want to see the locations of public restrooms on their way to pick up other supplies, so it would be helpful if they could seem them all on the same map.

**Comment by rahulgarg97** [comment] 2020-11-24 20:57
Hi @rossy312 , it's an intended thing. It's not a bug. The restrooms map is already there. We didn't want to clutter our map with so many things already there. Although we understand, it would have been better if we implemented it on our map. But didn't decide to do so.

Still, thanks for testing our app thoroughly. We would like you to mention this enhancement in the #general slack channel, since it's not a bug.

**Comment by rahulgarg97** [comment] 2020-11-24 20:59
Closing this issue.

**Closed as completed by rahulgarg97** 2020-11-24 20:59 UTC
