### ISSUE TITLE
SUGGESTION: Add a smooth scroll instead of the static one on the landing page for better UI/UX. Otherwise it looks amazing to me. Good work guys.

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/urban-thrifter#144] opened 2020-11-24 20:23 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Also you might face issue with smooth scroll for different browsers or maybe as a whole, so you can keep in mind to use a general script which works on all browsers.

## Steps to Reproduce

1. 

2. 

3. 

4.

**Comment by rahulgarg97** [comment] 2020-11-24 20:33
Hi, @ronakf11 , Thanks for your suggestion. We'll certainly take it into consideration. As this is not a bug, you can put a enhancement/suggestion note in the #general channel on Slack.

**Comment by rahulgarg97** [comment] 2020-11-24 20:50
Closing it as it's not a bug. But please mention it in the #general slack channel.

**Closed as completed by rahulgarg97** 2020-11-24 20:50 UTC
