### ISSUE TITLE
Suggestion: A description of the button's function on hovering above it

### ISSUE THREAD

**Issue by shrutiagarwal28** [gcivil-nyu-org/urban-thrifter#147] opened 2020-11-24 20:54 UTC
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

It would be good to see a a description of a button's functionality appear on hovering above it.

## Current Behavior

It's really good to see that the button icon's are very meaningful in themselves, and change design on hovering above them. But it would be good to see their description on hovering over it

## Steps to Reproduce

1.  I think the title attribute in html can be used within the button's tag

2. 

3. 

4.

**Comment by rahulgarg97** [comment] 2020-11-24 20:58
Hi @shrutiagarwal28 , thanks for pointing that out. Since, it's not a bug, our team would like you to mention this enhancement suggestion over slack #general channel.

Thanks for thoroughly testing our app!

Closing this issue.

**Closed as completed** 2020-11-24 20:58 UTC
